# Generated by Django 4.2.5 on 2023-10-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBecas', '0003_rol_usuario_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaBeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('cupo', models.PositiveIntegerField()),
                ('donantes', models.CharField(max_length=255)),
                ('coberturaEconomica', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipoBeca', models.CharField(max_length=50)),
                ('requisitos', models.TextField()),
            ],
        ),
    ]
