# Generated by Django 4.2.5 on 2023-11-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBecas', '0005_tipoconvocatoria_cronograma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoconvocatoria',
            name='nombre',
            field=models.CharField(choices=[('Abierta', 'Abierta'), ('Mixta', 'Mixta'), ('Cerrada', 'Cerrada')], max_length=100),
        ),
    ]
