# Generated by Django 4.2.5 on 2023-11-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBecas', '0006_alter_tipoconvocatoria_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronograma',
            name='tipo_convocatoria',
            field=models.CharField(choices=[('Abierta', 'Abierta'), ('Mixta', 'Mixta'), ('Cerrada', 'Cerrada')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tipoconvocatoria',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
